### ISSUE TITLE
大佬强悍的代码功底到底是如何练就的呀

### ISSUE THREAD

**Issue by zlonqi** [zl-cheng/CodeCraft2019#1]
本科小菜鸡，第一次关注华为软挑赛，在解题思路方面，对于判题器，调度器这些啥压根都想不到，更别说解决死锁了，赛后阅读过大佬们的天工之作，无论是解题逻辑还是代码功底都超强，大佬一个人能写出如此惊艳的解题来，简直惊为天人，有点好奇大佬是如何做到如此得心应手的

**Comment by zl-cheng** [comment]
大佬不敢当。。。路上的车一多就很容易死锁，会影响成绩的上限，自然就有写判题器的必要了（官方也给了很详细的任务书，摆明了想让大家复现一遍）。代码和策略选择方面感觉主要还是得多尝试。希望对你有帮助。
